### ISSUE TITLE
Where are effil.lua, libeffil.so/libeffil.dylib?

### ISSUE THREAD

**Issue by Amir-Arsalan** [loud-hound/woofer#102]
I am building a large Singularity container and it takes hours to make it. Before I install effil I would like to know where are the files effil.lua, libeffil.so/libeffil.dylib so that I can put a command in my script to copy those files into another location so that I can access them once the container is built. Would you please tell me where those files are once I compile effil so that I won't have to spend another couple of hours finding them and making the container again? Are they gonna be in the main effil folder? 

Another question: By copying those files to my project, do you mean I should simply do `cp effil.lua libeffil.so libeffil.dylib myProjectDir/`?

Thank you

**Comment by IUdalov** [comment]
Hi Amir!
Yep, it's simply `cp`. 
You can find them at `effil/src/lua/effil.lua` and `<path-to-you-cmakebuild>/libeffil.so` for Linux hosts. 
`libeffil.dylib` is `libeffil.so` replacement for MacOS X hosts.
You have to use either `libeffil.so` on Linux or `libeffil.dylib` on Mac. 
Good luck with your project.
