### ISSUE TITLE
build concurrency TCP/IP/HTTP server

### ISSUE THREAD

**Issue by webandbusiness** [loud-hound/woofer#117]
Hello, this is just a question, not issue.
I find effil so powerfull, i am using openresty server (nginx+lua scripting) with high concurency capacity,
Do you thing luajit, and effil can build high concurency server, with spawn threads as requests processing base.
Regards

**Comment by IUdalov** [comment]
I think Effil + LuaJIT can give great performance. 
But it is not easy to win against nginx.
nginx works as follows:
1. It creates master process and listens sockets.
2. Spawns  workers by forks. Now socket is present in multiple procceses. Only one of them will get incoming connection. Each worker has single thread.
3. By default nginx reuses Lua state in each worker.
 
This approach very efficient (as far as I now) and adopted by many other apps (e.g. Reddis).
1. Connections are dispatched by linux kernel.
2. No synchronization inside worker.
3. Reduced allocation. Lua state reused per requests by default.

If you take effil you can save a bit on interprocess communication (nginx does it), multithreading is less expensive usually. But you defiantly should reuse threads and be careful about connections dispatch.

You can try it!
I will be so happy if you efficiently implement it😉

**Comment by IUdalov** [comment]
@webandbusiness I am closing issue for now. Let's keep in touch.
