### ISSUE TITLE
 как встроить новый поток в код с++, чтобы функция foo запускалась в новом потоке? 

### ISSUE THREAD

**Issue by egor230** [loud-hound/woofer#124]
Очень восхищен Вашей библиотекой многопоточности Effil в lua. Возник вопрос: как встроить новый поток в код с++, чтобы функция foo запускалась в новом потоке? Очень хочу разобраться в механизме. Буду очень рад Вашему ответу. Спасибо.
`
#include<iostream>
#include<lua.hpp>
#include<threading.h>
using namespace std;
using namespace sol;
using namespace effil;

const char* LUA = 
R"(
foo()
)";
int foo(lua_State* L) {
	cout << "hi foo c++" << endl;
	return 0;
};

int embeds_sol(lua_State* L) {
	// start using sol with a pre-existing system
	state_view lua(L); // non-owning
//	runner = thread(foo);
	Thread::exportAPI(lua);
	lua.open_libraries(lib::base, lib::package); // открыть доп.библиотеки.
	lua.set("foo", foo); // вариант 2.

	//Thread::resume();
	lua.script(LUA);

	return 0; // все, что требуется для работы с необработанной функцией.
};

int main(int argc, char* argv[]) {
	lua_State* L = luaL_newstate();
	luaL_openlibs(L);
	embeds_sol(L);
	lua_close(L);

	return 0;
};
`

**Comment by mihacooper** [comment]
Спасибо за отзыв.

К сожалению, C++ API Effil'а на данный момент не подготовлен и не задокументирован. Поэтому я бы не рекомендовал его использовать. В зависимости от ваших целей, я бы выбрал один из двух вариантов.
1. Если нужно просто запустить выполнение скрипта в отдельном, то использовать стандартные потоки из `std`
```cpp
#include <thread>
...
int embeds_sol(lua_State* L) {
    state_view lua(L);
    lua.open_libraries(lib::base, lib::package);
    lua.set("foo", foo);

    std::thread t([&](){
        lua["foo"]();
    });
    t.join();
    return 0;
};
```

2. Если же внутри скрипта нужно использовать `effil`, то произвести его запуск через `Lua`
```cpp
// метод, который нужно будет экпортировать из effil.so,
// вам так же нужно будет слинковаться с effil.so
int luaopen_effil(lua_State* L);

int embeds_sol(lua_State* L) {
    luaopen_effil(L); // обязательное действие на данный момент

    auto result = lua.script(R"(
        local effil = require 'effil'
        return effil.thread(function() print("qwe") end)()
    )");
    assert(result.valid());

    auto thread = result.get<sol::table>();
    thread["wait"](thread); // нужно передать 'self'
    return 0;
};
```
Но в этом случае вам не удастся передать вашу функцию `foo` в новый поток. Каждый поток создает свой собственный lua state и использует сериализацию для передачи функций между state'ами. И т.к. Lua не различает C функции от скриптовых, то на данный момент у нас нет возможности передать C функцию между state'ами.
Выходом в данной ситуации будет создаyние динамической библиотеки из функций, который вам нужны в Lua и загружать её в state через `require`.

**Comment by mihacooper** [comment]
@egor230 , удалось ответить на ваш вопрос, закрываем issue?

**Comment by egor230** [comment]
> Спасибо за отзыв.
> 
> К сожалению, C ++ API Effil'а на данный момент не подготовлен и не задокументирован. Я бы не рекомендовал его использовать. В зависимости от ваших целей, я бы выбрал один из двух вариантов.
> 
> 1. Чтобы использовать стандартные потоки в отдельном. `std`
> 
> ```c++
> # include  < thread >
> ...
> int  embeds_sol ( lua_State * L) {
>     state_view lua (L);
>     Lua. open_libraries (lib :: base, lib :: package);
>     Lua. set ( " foo " , foo);
> 
>     std :: thread t ([&] () {
>         lua [ " foo " ] ();
>     });
>     т. join ();
>     вернуть  0 ;
> };
> ```
> 
> 1. Если же внутри скрипта нужно использовать `effil`, то произвести его запуск через`Lua`
> 
> ```c++
> // метод, который нужно будет извлекать из effil.so, 
> // вам нужно тоже слинковаться с effil.so 
> int  luaopen_effil (lua_State * L);
> 
> int  embeds_sol ( lua_State * L) {
>      luaopen_effil (L); // обязательное действие на данный момент
> 
>     автоматический результат = lua. script ( R "(
>          локальный effil = require 'effil' 
>         return effil.thread (function () print (" qwe ") end) () 
> )" );
>     assert (результат. valid ());    
> 
>     автоматическая нить = результат. get <sol :: table> ();
>     нить [ " ждать " ] (нить); // нужно передать 'self' 
>     return  0 ;
> };
> ```
> 
> Передать вашу функцию `foo`в новый поток. Каждый поток создает свой собственный штат Луа и использует сериализацию для передачи функций между штатами. И т.к. У нас нет возможности передавать функции C между состояниями. 
> Выход из данной ситуации будет создавать динамическую библиотеку из функций, которые вам нужны в Lua и загружать в состояние через `require`.

Спасибо большое за Ваш ответ. Я не очень понимаю как установить библиотеку effil, попытался её собрать через Сmake, толку нет. Такая же ситуация была с библиотекой lanes http://www.cyberforum.ru/lua/thread2483405.html , понимаете, мне очень нужна многопоточность в моём проекте, lua плагин для gta vc https://vk.com/gtabuilder?w=wall-56513456_513 .?. Её можно реализовать только с помощью сторонней библиотеки. Очень буду рад Вашему ответу. Спасибо.

**Comment by mihacooper** [comment]
Могу посоветовать:
1. Посмотреть на наш конфиг сборки под винду на сервисе [appveyor](https://www.appveyor.com/). Конфиг [тут](https://github.com/effil/effil/blob/master/appveyor.yml).
2. Либо использовать [luarocks](https://luarocks.org/)

**Comment by egor230** [comment]
спасибо большое за Ваш ответ. установил luarocks. при попытки установить effil, выдает, что не может найти ее для lua 5.3.5
вот видео записал как не получается. https://www.youtube.com/watch?v=kn4ifVnyqT8&feature=youtu.be
помогите, пожалуйста.

**Comment by mihacooper** [comment]
верятнее всего вы поставили luarocks для другой версии Lua. Советую так же глянуть на такой инструмент как [hererocks](https://github.com/mpeterv/hererocks). Он позволяет создавать окружение для конкретной версии lua и luarocks

**Comment by egor230** [comment]
спасибо большое за Ваш ответ уважаемый mihacooper. было бы здорово, если можно было бы скачать уже готовую сборку под разные версии lua.

хотя бы видео инструкция для нубов, как собрать.
