### ISSUE TITLE
при попытке собрать проект в MVS 2019 выходит ошибка  Ошибка	C1083

### ISSUE THREAD

**Issue by egor230** [loud-hound/woofer#128]
Здравствуйте, пытаюсь собрать effil через cmake, скачал репозиторий, скопировал sol в папку libs, указал папку с lua 5.3.5. при попытке собрать проект в MVS 2019 выходит ошибка 
Ошибка	C1083	 Не удается открыть файл включение: sol.hpp: No such file or directory,	effil	C:\projects\effil\src\cpp\utils.h

Подскажите, пожалуйста,  как решить эту проблему?

Когда проект соберется он будет effil.dll или effil.lua?
![Screenshot](https://user-images.githubusercontent.com/32921166/62862807-630e5e80-bd20-11e9-8300-5609858998b2.png)

**Comment by mihacooper** [comment]
в ошибке сказано, что вам не хватает заголовочного файла от `sol2`. Он подключен к нашему проекту как [git submodule](https://git-scm.com/book/ru/v1/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BC%D0%B5%D0%BD%D1%82%D1%8B-Git-%D0%9F%D0%BE%D0%B4%D0%BC%D0%BE%D0%B4%D1%83%D0%BB%D0%B8). По всей видимости вы его не выкачали.

надо либо при клонировании указывать `git clone ... --recurse-submodules`, либо в уже склонированном репозитории делать `git submodule init` и `git submodule update`

по итогу все директории в `./libs/*` должны быть не пустые

**Comment by mihacooper** [comment]
результат сборки - `effil.dll`

**Comment by egor230** [comment]
Спасибо Вам огромное, уважаемый mihacooper
Наконец-то собрал!!!!!!!!!! Очень рад, столько мучался…

Использую среду разработки IntelliJ IDEA Community Edition 2019.1.3, скинул в C:\Program Files\lua effil.dll. запустил lua скрипт, ошибка. Подскажите, пожалуйста, как исправить?
![Screenshot](https://user-images.githubusercontent.com/32921166/62866561-7a524980-bd2a-11e9-8255-55784ea1431b.png)

**Comment by mihacooper** [comment]
почитайте как работает `package.path` и `package.cpath` в lua. Скорей всего у вас путаница в путях.

**Comment by egor230** [comment]
Спасибо за совет. В мой компьютер, свойства, дополнительные параметры системы, переменные среды, добавил новую переменную  LUA_CPATH значение задал c:\Program Files\lua\?.dll все равно не видит require не видит модул 'effil', помогите, пожалуйста, советом.
