### ISSUE TITLE
Sleep a thread

### ISSUE THREAD

**Issue by Chipsterjulien** [loud-hound/woofer#131]
Hello
I try to sleep a thread with socket.sleep or socket.select(nil, nil, x) but, the only way I found is to use os.execute("sleep x") where x is a number as follow:
```lua
local effil = require("effil")

-- channel allow to push data in one thread and pop in other
local channel = effil.channel()

-- writes some numbers to channel
function producer(channel)
    for i = 1, 5 do
        print("push " .. i)
        channel:push(i)
        os.execute("sleep " .. tostring(i))
    end
    channel:push(nil)
end

-- read numbers from channels
local function consumer(channel)
    local i = channel:pop()
    while i do
        print("pop " .. i)
        i = channel:pop()
    end
end

-- run producer
local thr = effil.thread(producer)(channel)

-- run consumer
consumer(channel)

thr:wait()
```
So, the code is bad. Is there another solution ?
Thank for your help and nice job for effil

Best regards
Julien

**Comment by mihacooper** [comment]
Hello
If I understand you right you need a sleep function.
And we have one. Read about it here:
https://github.com/effil/effil/blob/master/README.md#effilsleeptime-metric

Correct me if I don't understand you and please close the issue if problem solved.

**Comment by Chipsterjulien** [comment]
Hello
I saw it yes but here, with the same code above and I replace:
```lua
os.execute("sleep " .. tostring(i))
```
by
```lua
effil.sleep(2, "s")
```
the program freeze once effil.sleep is met the first time

**Comment by mihacooper** [comment]
Now I understand you.

Let me show you the problem. I suppose you are using current stable release from luarocks. The effil-1.0.0 does not support upvalues so it does not capture this upvalue - `local effil = require("effil")`

So when you run your code actually you got error in another thread. Try to print the result of thread:
```lua
local effil = require("effil")

function producer(channel)
    -- ...
    print(effil) -- step #1
    effil.sleep() -- step #2
    -- ..
end

local thr = effil.thread(producer)(channel)
print(thr:wait())
```
The result will be
```lua
nil
lua: error: /tmp/sample.lua:5: attempt to index upvalue 'effil' (a nil value)
```


To solve the problem you should choose one of these solution:
 - Include effil module in each thread (remember that each thread has it's own Lua state)
```lua
function producer(channel)
    local effil = require("effil")
    ...
end
```
 - Build the current version of effil from github master branch. The upvalues support is already implemented but still was not released (sorry for that). The [instruction](https://github.com/effil/effil/blob/master/README.md#how-to-install). 
```lua
local effil = require("effil")

function producer(channel)
    print(effil) -- is not nil
end

local thr = effil.thread(producer)(channel)
thr:wait()
```

**Comment by Chipsterjulien** [comment]
Thanks for your help, it works perfectly

I have another question about userdata but I will open a new issue
