### ISSUE TITLE
Method to turn an effil.table into a normal table

### ISSUE THREAD

**Issue by adrfantini** [loud-hound/woofer#132]
Hi and thanks for `effil`!

Sometimes it's be nice to be able to turn an `effil.table` back into a normal `table`, for example when using external libraries that check for the `type()` of an input.

One can do this with a simple loop, bu it's a bit tedious (especially for nested tables). Can you provide a function to do this? 

(if it's not there already and I missed it!)

Thanks!

**Comment by mihacooper** [comment]
Thanks for this issue. We used to think about such function a lot of times and still don't implement it.
We should finally make it =)
