### ISSUE TITLE
userdata

### ISSUE THREAD

**Issue by Chipsterjulien** [loud-hound/woofer#133]
Hello

Is it planned to manage userdata ? I need to use socket (tls) and separate incoming data and sent data.
Unfortunately, socket return userdata and I am blocked

Best regards
Julien

**Comment by mihacooper** [comment]
Hello.

The userdata management is not trivial task, cause Lua does not provide any generalizaed API for userdata. We don't know how to copy userdata from one Lua state to another in general.

So, looks like the only way is to compile Effil with luasocket (or any other module) support.
We will think about writing a documentation for that.

**Comment by Chipsterjulien** [comment]
Thank you for your reply
I look forward to your doc
