### ISSUE TITLE
How to use next() with effil?

### ISSUE THREAD

**Issue by adrfantini** [loud-hound/woofer#135]
I have a program in which I need to set the metatable so that `pairs()` does not iterate over functions. Something like this seems to work OK with normale tables:
```
local mt = { -- metatable
    __pairs = function(t) -- do NOT iterate with pairs over functions!
            local k=nil
            return function ()
                local v
                repeat k,v = next(t,k) until type(v) ~= 'function' or k == nil
                return k,v
            end
        end
}
setmetatable({}, mt)
```

However when setting the metatable for an effil table (`effil.setmetatable`) I have the following error:
```
bad argument #1 to 'next' (table expected, got sol.effil::SharedTable*)
```

How can I make this work? Thanks in advance!

**Comment by mihacooper** [comment]
Thanks for that question. It's our mistake that we  don't have impl for `next`.

Currently you can only use `effil.pairs` and `effil.ipairs` functions.

I will try implement `effil.next` soon.

**Comment by adrfantini** [comment]
Thanks!

> Currently you can only use `effil.pairs` and `effil.ipairs` functions.

As for what I want to do (loop using `pairs` only over non-function items), do you know if there is any way I can do this without `effil.next`?

**Comment by mihacooper** [comment]
for right now I see the only one solution
```lua
local effil = require "effil"

function my_pairs(t)
    local next_func = effil.pairs(t)
    return function (t, k)
        local v
        repeat k,v = next_func(t,k) until type(v) ~= 'function' or k == nil
        return k,v
    end, t
end

local t = effil.table{
    a = 2,
    b = function()end,
    c = 3,
    d = function()end,
}

for k, v in my_pairs(t) do
    print(k,v)
end
```
