### ISSUE TITLE
Effil threads compatibility with Lua "classes"

### ISSUE THREAD

**Issue by adrfantini** [loud-hound/woofer#151]
I'm trying to make Effil threads work with Lua objects mimicking classes.

Here is a MRE. I have a file called `timers.lua` with the following code:

```lua
effil = require('effil')

_timersContainerClass = effil.table()

-- Metamethods
function _timersContainerClass:__index(key)
    local value = effil.rawget(self, key) -- workaround for effil __index problem in this effil 0.1.0, see #139
    if value ~= nil then
        return value
    end
    return _timersContainerClass[key]
end

-- Object creation method.
function _timersContainerClass:new()
    local outer = effil.table()
    effil.setmetatable(outer, self)
    return outer
end

function _timersContainerClass:getParent()
    return tostring(_timersContainerClass)
end

```

This basically creates a global class `_timersContainerClass`.
Now, if I try to use it in an Effil thread:

```lua
effil = require('effil')

require('timers')

-- Create an object of the class
t = _timersContainerClass:new()

function checkExpired(t, _timersContainerClass)
    effil = require "effil" -- MUST be global (?)
    print('INSIDE CLASS', _timersContainerClass) -- OK, xyz as outside
    print('INSIDE PARENT1', _timersContainerClass:getParent()) -- nil
    print('INSIDE PARENT2', t:getParent()) -- fails
end

print('OUTSIDE CLASS', _timersContainerClass) -- OK, xyz
print('OUTSIDE PARENT1', _timersContainerClass:getParent()) -- OK, xyz
print('OUTSIDE PARENT2', t:getParent()) -- OK, xyz

effil.sleep(1, 's')

thread = effil.thread(checkExpired)(t, _timersContainerClass)

effil.sleep(1, 's')

thread:status() -- Shows where it failed: in __index while trying t:getParent()
```

If you run this, you'll see that the three outside `print`s work as expected, and that they return the same table as the first inside `print`. But the second and third thread `print` return `nil` and error respectively. Why is that, and how to fix it?

**Comment by adrfantini** [comment]
If instead of `_timersContainerClass` I use everywhere, including in the class definition, `effil.G._timersContainerClass`, everything seems to be working:

Class:
```lua
effil = require('effil')

effil.G._timersContainerClass = effil.table()

-- Metamethods
function effil.G._timersContainerClass:__index(key)
    local value = effil.rawget(self, key) -- workaround for effil __index problem in this effil 0.1.0, see #139
    if value ~= nil then
        return value
    end
    return effil.G._timersContainerClass[key]
end

-- Object creation method.
function effil.G._timersContainerClass:new()
    local outer = effil.table()
    effil.setmetatable(outer, self)
    return outer
end

function effil.G._timersContainerClass:getParent()
    return tostring(effil.G._timersContainerClass)
end
```
Code:
```lua
effil = require('effil')

pl = effil.table()

require('timersTEST2')

t = effil.G._timersContainerClass:new()

function checkExpired(t)
    effil = require "effil" -- MUST be global (?)
    print('INSIDE CLASS', effil.G._timersContainerClass) -- OK, xyz as outside
    print('INSIDE PARENT1', effil.G._timersContainerClass:getParent()) -- OK, xyz
    print('INSIDE PARENT2', t:getParent()) -- OK, xyz
end

print('OUTSIDE CLASS', effil.G._timersContainerClass) -- OK, xyz
print('OUTSIDE PARENT1', effil.G._timersContainerClass:getParent()) -- OK, xyz
print('OUTSIDE PARENT2', t:getParent()) -- OK, xyz

effil.sleep(1, 's')

thread = effil.thread(checkExpired)(t)

effil.sleep(1, 's')

thread:status() -- Shows where it failed: in __index while trying t:getParent()
```

But this is not what I want, since I cannot use `effil.G` to export the class.
I do not want to export every class I use to every thread I defined, since there are many.

**Comment by mihacooper** [comment]
Hello, adrfantini!

The problem caused by `_G` in your function's upvalue again.
You have declared your class global variable:
```
_timersContainerClass = effil.table()
```
And after that references it in function:
```
function _timersContainerClass:getParent()
    return tostring(_timersContainerClass)
end
```
So, `_timersContainerClass:getParent` has `_G` in it's upvalues. But it does not work in Lua, [docs here](https://github.com/effil/effil#functions-upvalues).

To fix the problem you should declare it as a local variable
`local _timersContainerClass = effil.table()`.
And it's better always (where it's possible) do that.

After that you can expose `_timersContainerClass` like that:
 `_timersContainerClass = require 'timers'` - preferable way (make `return _timersContainerClass`  in your timers module)
Or like that:
`_G._timersContainerClass = _timersContainerClass` - at the end of 'timers' module. Not really cool, but still works

**Comment by adrfantini** [comment]
Once again, thank you very much for the time you've taken to dispel my doubts. It's quite clear now!

**Comment by mihacooper** [comment]
Hope, problem solved, if not feel free to open another issue
