### ISSUE TITLE
effil.version is 0.1.0

### ISSUE THREAD

**Issue by adrfantini** [loud-hound/woofer#152]
Hi, I installed `effil` using `luarocks install effil` on a new system. `luarocks` correclty installed version 1.1.0.
However:
```lua
> effil = require 'effil'
> effil.version
0.1.0
```
Why?

**Comment by mihacooper** [comment]
That's known bug caused by hardcoded version in sources. I'll try to automate version update taking it from git tags.

Thanks for reminding.

**Comment by mihacooper** [comment]
Fixed in version 1.1.1

**Comment by adrfantini** [comment]
Thanks! Keep up the good work!

**Comment by adrfantini** [comment]
Uhm, I installed Effil 1.2.0 from Luarocks and this bug reappeared? Maybe something weird with my system?
How can I check?

**Comment by mihacooper** [comment]
No, seems like I forgot to update it, again.
We still didn't automate it =\
