### ISSUE TITLE
Which is more efficient, channels or tables?

### ISSUE THREAD

**Issue by adrfantini** [loud-hound/woofer#156]
I have a usecase in which I need to have a slave thread looping continuously, reading some values and calculating a result.
Occasionally, the master thread will grab this result and use for its own calculations.

What is the most efficient approach in this case? Sharing an `effil.table`, with a field storing the current value, or sharing a thread of size 1, which gets emptied (`pop`) and refilled (`push`) at every loop by the slave?

**Comment by mihacooper** [comment]
In general channels should be more efficient than tables. Moreover, they gives you efficient waiting functionality instead of active polling of tables.
But if you need repeatedly read something in slave thread without changes than it's better to store it in table. Cause each time when you push into channel Effil will copy data and maybe serialize it if it's lua table.

**Comment by adrfantini** [comment]
Thank you. In this case I would need only to exchange numerical values, so I should not need serialisation, but I do not need active waiting: the master thread should take whichever last value the slave generated.

I would think channels would be more suited for this. However, an issue pops up. if setting the channel size to 1 (as the master needs only the latest value), the slave should, at every loop, check if the value is still there (the master has not read it yet) and if not, `pop` it in order to update it. This does not seem very efficient, and might not be atomic maybe. Is there any way to "overwrite" the current value of a channel of size 1, so that it always only stores the latest updated value?

**Comment by mihacooper** [comment]
No, you cann't overwrite values in channel, it's simple FIFO queue.
You described scenario where effil.table will suit perfectly.

**Comment by adrfantini** [comment]
Thank you for the clarification.

**Comment by adrfantini** [comment]
Oh, one more thing. In general, is it good to share a large-ish table among threads, or is it better to create a single small table just for this?

Say that I have a setup with a master and 5 slave threads, each of which reads only one value and returns only one value. Is it significantly more efficient to have 5 separate tables (each with two values: input and output), or can I define one single "sharing" table (with 10 values: 5 inputs and 5 outputs) in the master?

**Comment by mihacooper** [comment]
Separate table will be better, cause each slave thread will block table on write operation. In case it's a single table they will wait each other.

**Comment by adrfantini** [comment]
Ok that was basically my question: if the whole table was blocked, or the single values inside each table. That clarifies it. Thank you again!
