### ISSUE TITLE
Shouldn't link to LUA_LIBRARY on Linux

### ISSUE THREAD

**Issue by ylme** [loud-hound/woofer#158]
The line should be deleted on Linux.

https://github.com/effil/effil/blob/master/CMakeLists.txt#L44

On linux, the basic use is that the host execute file statically link to static library liblua.a and export all its symbols, like this in the Lua Makefile. 

```
# link lua executable file with -Wl,-E
linux:
	$(MAKE) $(ALL) SYSCFLAGS="-DLUA_USE_LINUX" SYSLIBS="-Wl,-E -ldl -lreadline"
```

Then the C extended libray .so file should not link with liblua.a , if does, then two lua obj code exists, which is absolutely wrong.

**Comment by mihacooper** [comment]
fixed https://github.com/effil/effil/pull/167
