### ISSUE TITLE
Why are some local functions dumpable to effil.table, and some not? How to tell one from the other?

### ISSUE THREAD

**Issue by adrfantini** [loud-hound/woofer#161]
Probably related with #160.

I do not understand why some functions seem work in an `effil.table`, and some don't. It makes using `effil` extremely hard, because I cannot plan in advance the code architecture as I am lacking this important detail.

See this example below:
```lua
local socket = require("socket")
local gettime = socket.gettime

local some_local_function = function() print(23) end

local effil = require('effil')
local foo = effil.table()

foo.test = function()
  print(gettime()) -- does not work
  print(socket.gettime()) -- does not work
  print(some_local_function()) -- works (if the above is commented)
end

print('TESTING') -- NOT REACHED, as the assignment fails

foo.test()
```
Output:
```
lua: effil.table: bad function upvalue #2 (Unable to dump Lua function: Unknown (1))
stack traceback:
        [C]: in metamethod '__newindex'
        tests/test_tmp.lua:29: in main chunk
        [C]: in ?
```

However, if `gettime` (or `socket`) is defined _globally_, then... it works! However, defining functions globally is bad practice and would, I think, cause issues in case `effil.threads` are used.
The [documentation](https://github.com/effil/effil#functions-upvalues) regarding this is not very clear to me, sorry.

**Comment by mihacooper** [comment]
Hi, the problem is that effil is not able to transmit C-functions between Lua states. So, you just can't put C-function in any effil object.
The only solution is to include required modules in place where you want to use it. Like that:
```lua
local some_local_function = function() print(23) end

local effil = require('effil')
local foo = effil.table()

foo.test = function()
  local socket = require("socket")
  gettime = socket.gettime

  print(gettime())
  print(socket.gettime())
  print(some_local_function())
end

print('TESTING') -- NOT REACHED, as the assignment fails

foo.test()
```
Thanks for feedback we need to describe this in documentation better

**Comment by adrfantini** [comment]
Thank you for your quick reply. That helps.
I'll try to see how to approach this in an efficient way.
Feel free to close or to keep this open to update the doc.

**Comment by mihacooper** [comment]
Implemented
