### ISSUE TITLE
Trying to build for Windows produces an error, any idea what it is?

### ISSUE THREAD

**Issue by ghost** [loud-hound/woofer#174]
Hi! I want to use this with LuaJIT, and I don't have luarocks installed on my Windows machine, and my "installation" of LuaJIT consisted in creating a folder for the executable and adding it to PATH.

Anyway, when attempting to build effil under these conditions, I get the following message:

> CMake Error at C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
>     Could NOT find Lua (missing: LUA_LIBRARIES LUA_INCLUDE_DIR)
> Call Stack (most recent call first):
>      C:/Program Files/CMake/share/cmake-3.24/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)
>  C:/Program Files/CMake/share/cmake-3.24/Modules/FindLua.cmake:236 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
>  CMakeLists.txt:13 (find_package)

Any idea what it is? 

--------------------------------------------

Edit: It seems the instruction find_package(Lua REQUIRED) is not being successfully executed, almost certainly because of how I installed LuaJIT (I simply copied it into a folder called C:\\LuaJIT-2.1 and then added that folder to PATH, my LuaJIT executable is called luajit.exe, there is a dynamic library in the folder called lua51.dll). 

Do you happen to know how I can edit CMakeLists so it can find and use the library? I don't have a CMake package anywhere on that folder so I don't think it's going to find any package.

-------------------------------------------

Edit2: I tried changing that line to find_library and manually pointing it to the lua51.dll in the LuaJIT folder using cmake gui, but then the generated solution has a compile error (cannot find lua.hpp error). I'm really stuck on this issue.

**Comment by mihacooper** [comment]
Hello, @kunrii.

Here you can find prebuilt binaries: https://github.com/effil/effil/releases
And here you can find how do we build it for Windows platform: https://github.com/effil/effil/blob/master/.github/workflows/win_ci.yml
