### ISSUE TITLE
Add Lua API for GC

### ISSUE THREAD

**Issue by mihacooper** [loud-hound/woofer#20]
Analize and provide Lua API for internal GC (use Lua's GC API as an example)

**Comment by IUdalov** [comment]
I suppose this api will be enough:
```
effil.gc.collect() -- directly invoke GC
effil.gc.step() -- set&get GC step per allocation.
effil.gc.stop()
effil.gc.resume()
effil.gc.status()
```
What do you think @mihacooper?

**Comment by mihacooper** [comment]
Agree. Maybe not "stop" but "pause". That's more clear IMHO

**Comment by IUdalov** [comment]
Fixed
