### ISSUE TITLE
Fix&Simplify threads implementation

### ISSUE THREAD

**Issue by IUdalov** [loud-hound/woofer#29]
1. Get rid of active waiting in ` LuaThread::wait` and `luaHook`. Use conditional variable or mutex instead.
2. Get rid from detach. Use implicit detach. 
3. A-B-A problem. Cancel then resume is may be ok (!!!).
4. May be get rid of `ThreadFactory`. Now logic is quite complicated 😟.  `ThreadFactory` just captures this state variable and provide some configuration. Why not to hide it in `LuaThread`? `LuaThread::luaHook` and `LuaThread::work` have to be free functions!

**Comment by mihacooper** [comment]
Problem solved
