### ISSUE TITLE
Rewrite documentation to GitHub Wiki

### ISSUE THREAD

**Issue by mihacooper** [loud-hound/woofer#83]

**Comment by aoyawale** [comment]
please create the github wiki so it can be git cloned and worked on.

**Comment by mihacooper** [comment]
@jlozadad , done!

**Comment by aoyawale** [comment]
need to change the permissions on it :P https://help.github.com/articles/changing-access-permissions-for-wikis/ can't push to it.

**Comment by mihacooper** [comment]
@jlozadad , okay let's try)

**Comment by aoyawale** [comment]
still can't push
`
git push     
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/effil/effil.wiki.git/'
`

**Comment by mihacooper** [comment]
@jlozadad i did me best)) that's strange. Maybe you need to way for sometime...

**Comment by mihacooper** [comment]
Oh, maybe you need to

**Comment by mihacooper** [comment]
Github's wiki edit permissions pretty strange. Maybe it's better to use readthedocs.

**Comment by aoyawale** [comment]
that works for me.

**Comment by mihacooper** [comment]
@jlozadad , wiki starts work?

**Comment by aoyawale** [comment]
looks like I can edit the github wiki through the UI but, can't git push.

**Comment by mihacooper** [comment]
It's not cool that we are not able to manage Wiki changes. We don't get an updates and here is no review

**Comment by aoyawale** [comment]
that is correct.

**Comment by mihacooper** [comment]
So, check out [readthedocs](https://readthedocs.org) they solve this problem

**Comment by mihacooper** [comment]
@jlozadad, due to Github Wiki is not very good solution for documentation I will close this issue and deactivate our Wiki.
