### ISSUE TITLE
Submodule instruction is missing from readme

### ISSUE THREAD

**Issue by luizcavalcanti** [loud-hound/woofer#92]
I spent some time trying to find sol library as a dynlib on mac before realizing it is actually referenced as a submodule on this repo. 

I propose to put a `git submodule update --init` instruction on README.md  a submodule made the submodule step explicit in the README so new people can have a easier time.

(I actually already have a pull request ready, just following CONTRIBUTING.md, and waiting for confirmation if it's really an issue :) )

**Comment by mihacooper** [comment]
That's a good suggestion, but it's better to use `git clone --recursive`

**Comment by luizcavalcanti** [comment]
I personally like it less, but I'm fine as long as instrucions work if followed thoroughly :)
